# Generated by Django 4.2.21 on 2025-06-19 06:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_inversiones_customuser_rut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Este correo electrónico ya está en uso.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rut',
            field=models.CharField(error_messages={'unique': 'Este RUT ya está registrado.'}, help_text='Formato: 12.345.678-9', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use: 12.345.678-9', regex='^\\d{1,3}(?:\\.\\d{3}){2}-[\\dkK]$')], verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(error_messages={'unique': 'Este número de teléfono ya está registrado.'}, max_length=15, unique=True, verbose_name='Teléfono'),
        ),
    ]
